In [ ]:
import pandas as pd
books=pd.read_csv('/content/books.csv')
books.head(8)

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...
5,6,11870085,11870085,16827462,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,...,2346404,2478609,140739,47994,92723,327550,698471,1311871,https://images.gr-assets.com/books/1360206420m...,https://images.gr-assets.com/books/1360206420s...
6,7,5907,5907,1540236,969,618260307,9.780618e+12,J.R.R. Tolkien,1937.0,The Hobbit or There and Back Again,...,2071616,2196809,37653,46023,76784,288649,665635,1119718,https://images.gr-assets.com/books/1372847500m...,https://images.gr-assets.com/books/1372847500s...
7,8,5107,5107,3036731,360,316769177,9.780317e+12,J.D. Salinger,1951.0,The Catcher in the Rye,...,2044241,2120637,44920,109383,185520,455042,661516,709176,https://images.gr-assets.com/books/1398034300m...,https://images.gr-assets.com/books/1398034300s...

In [ ]:
books.drop(columns=['id','best_book_id','work_id','books_count','isbn','isbn13','original_publication_year','ratings_count','work_ratings_count','work_text_reviews_count','ratings_1','ratings_2','ratings_3','ratings_4','ratings_5','image_url','small_image_url'],inplace=True)

In [ ]:
books.head()

,book_id,authors,original_title,title,language_code,average_rating
0,2767052,Suzanne Collins,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34
1,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44
2,41865,Stephenie Meyer,Twilight,"Twilight (Twilight, #1)",en-US,3.57
3,2657,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,eng,4.25
4,4671,F. Scott Fitzgerald,The Great Gatsby,The Great Gatsby,eng,3.89

In [ ]:
books.drop(columns=['average_rating','language_code'],inplace=True)

In [ ]:
books.head(20)

,book_id,authors,original_title,title
0,2767052,Suzanne Collins,The Hunger Games,"The Hunger Games (The Hunger Games, #1)"
1,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...
2,41865,Stephenie Meyer,Twilight,"Twilight (Twilight, #1)"
3,2657,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird
4,4671,F. Scott Fitzgerald,The Great Gatsby,The Great Gatsby
5,11870085,John Green,The Fault in Our Stars,The Fault in Our Stars
6,5907,J.R.R. Tolkien,The Hobbit or There and Back Again,The Hobbit
7,5107,J.D. Salinger,The Catcher in the Rye,The Catcher in the Rye
8,960,Dan Brown,Angels & Demons,"Angels & Demons (Robert Langdon, #1)"
9,1885,Jane Austen,Pride and Prejudice,Pride and Prejudice
10,77203,Khaled Hosseini,The Kite Runner,The Kite Runner
11,13335037,Veronica Roth,Divergent,"Divergent (Divergent, #1)"
12,5470,"George Orwell, Erich Fromm, Celâl Üster",Nineteen Eighty-Four,1984
13,7613,George Orwell,Animal Farm: A Fairy Story,Animal Farm
14,48855,"Anne Frank, Eleanor Roosevelt, B.M. Mooyaart-D...",Het Achterhuis: Dagboekbrieven 14 juni 1942 - ...,The Diary of a Young Girl
15,2429135,"Stieg Larsson, Reg Keeland",Män som hatar kvinnor,"The Girl with the Dragon Tattoo (Millennium, #1)"
16,6148028,Suzanne Collins,Catching Fire,"Catching Fire (The Hunger Games, #2)"
17,5,"J.K. Rowling, Mary GrandPré, Rufus Beck",Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...
18,34,J.R.R. Tolkien,The Fellowship of the Ring,The Fellowship of the Ring (The Lord of the Ri...
19,7260188,Suzanne Collins,Mockingjay,"Mockingjay (The Hunger Games, #3)"

In [ ]:
books.isnull().sum()

book_id             0
authors             0
original_title    585
title               0
dtype: int64

In [ ]:
# Step 1: Fill in title_clean using original_title if available, else use title
books['title_clean'] = books['original_title'].fillna(books['title'])

In [ ]:
# Step 2: Keep only the cleaned title version, and rename it to 'title'
books = books[['book_id', 'title_clean', 'authors']]
books.rename(columns={'title_clean': 'title'}, inplace=True)

<ipython-input-21-4122181027>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books.rename(columns={'title_clean': 'title'}, inplace=True)

In [ ]:
books.head()

,book_id,title,authors
0,2767052,The Hunger Games,Suzanne Collins
1,3,Harry Potter and the Philosopher's Stone,"J.K. Rowling, Mary GrandPré"
2,41865,Twilight,Stephenie Meyer
3,2657,To Kill a Mockingbird,Harper Lee
4,4671,The Great Gatsby,F. Scott Fitzgerald

In [ ]:
books.isnull().sum()

book_id    0
title      0
authors    0
dtype: int64

In [ ]:
book_tags=pd.read_csv('/content/book_tags.csv')
tags=pd.read_csv('/content/tags.csv')
book_tags.isnull().sum()
tags.isnull().sum()

tag_id      0
tag_name    0
dtype: int64

In [ ]:
book_tags.isnull().sum()

goodreads_book_id    0
tag_id               0
count                0
dtype: int64

In [ ]:
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [ ]:
tags.head(50)

    tag_id                     tag_name
0        0                            -
1        1                         --1-
2        2                        --10-
3        3                        --12-
4        4                       --122-
5        5                       --166-
6        6                        --17-
7        7                        --19-
8        8                         --2-
9        9                       --258-
10      10                         --3-
11      11                        --33-
12      12                         --4-
13      13                         --5-
14      14                        --51-
15      15                         --6-
16      16                        --62-
17      17                         --8-
18      18                        --99-
19      19  --available-at-raspberrys--
20      20                      -2001--
21      21                     -calif--
22      22                       -d-c--
23      23                        -dean
24      24                    -england-
25      25                     -fiction
26      26                   -fictional
27      27                  -fictitious
28      28                   -football-
29      29                      -george
30      30                         -gr-
31      31                     -history
32      32                   -imaginary
33      33                      -italy-
34      34                        -la--
35      35                         -los
36      36                      -mass--
37      37                     -murder-
38      38                       -n-y--
39      39                 -non-poetry-
40      40                  -performing
41      41                        -post
42      42                 -psychology-
43      43                        -read
44      44                      -single
45      45                    -specific
46      46                  -television
47      47                            0
48      48             0-0-0-0cant-find
49      49                    0-0-bingo

In [ ]:
book_tags = book_tags.merge(tags, on='tag_id', how='left')

In [ ]:
# Sort so most frequent tags appear first
book_tags_sorted = book_tags.sort_values(by=['goodreads_book_id', 'count'], ascending=[True, False])

# Group into single string per book
book_tag_strings = book_tags_sorted.groupby('goodreads_book_id')['tag_name'].apply(lambda x: ' '.join(x.astype(str))).reset_index()
book_tag_strings.columns = ['goodreads_book_id', 'tags']

In [ ]:
books = books.merge(book_tag_strings, left_on='book_id', right_on='goodreads_book_id', how='left')

In [ ]:
books.head()

,book_id,title,authors,goodreads_book_id,tags
0,2767052,The Hunger Games,Suzanne Collins,2767052,favorites currently-reading young-adult fictio...
1,3,Harry Potter and the Philosopher's Stone,"J.K. Rowling, Mary GrandPré",3,to-read favorites fantasy currently-reading yo...
2,41865,Twilight,Stephenie Meyer,41865,young-adult fantasy favorites vampires ya fict...
3,2657,To Kill a Mockingbird,Harper Lee,2657,classics favorites to-read classic historical-...
4,4671,The Great Gatsby,F. Scott Fitzgerald,4671,classics favorites fiction classic books-i-own...

In [ ]:
import re

def clean_tags(text):
    if isinstance(text, str):
        tags = text.split()
        tags = [re.sub(r'^-+|-+$', '', tag) for tag in tags]        # remove dashes
        tags = [tag.lower() for tag in tags if len(tag) > 2]        # keep meaningful tags
        tags = [re.sub(r'[^a-zA-Z\-]', '', tag) for tag in tags]    # remove special characters
        return ' '.join(tags)
    return ''

books['tags'] = books['tags'].apply(clean_tags)

In [ ]:
books['tags'][2]

'young-adult fantasy favorites vampires fiction to-read paranormal books-i-own vampire twilight paranormal-romance supernatural teen urban-fantasy owned-books stephenie-meyer my-books favourites werewolves i-own chick-lit re-read ya-fiction twilight-saga default young-adult-fiction sci-fi-fantasy contemporary twilight-series books love ya-fantasy horror book-club my-library novels favorite favorite-books teen-fiction guilty-pleasures high-school read-more-than-once fantasy-sci-fi stephanie-meyer vamps own-it ya-books my-favorites shelfari-favorites library audiobook kindle finished all-time-favorites read-in- love-triangle -stars vampire-books read-in- reread ya-lit abandoned never-again movies audiobooks science-fiction finished-series ya-paranormal guilty-pleasure currently-reading movie completed-series english sci-fi already-read did-not-finish ebook on-my-shelf pnr have book-to-movie meh paranormal-fantasy bookshelf drama my-bookshelf ya-romance sries youngadult favorite-series first-in-series young-adults books-i-have dnf faves fantasy-paranormal scifi-fantasy romantic american'

In [ ]:
def refine_tags(tag_str):
    if not isinstance(tag_str, str):
        return ''

    tags = tag_str.lower().split()
    cleaned_tags = []

    for tag in tags:
        tag = tag.strip('-')  # remove leading/trailing dashes
        if len(tag) < 3 or tag in {'d', 'read', 'default', 'my'}:
            continue  # remove noise

        # normalize common variations
        if 'sci' in tag and 'fi' in tag:
            tag = 'scifi'
        elif tag in ['favourite', 'favorites', 'favourites', 'favs', 'faves']:
            tag = 'favorite'
        elif tag.startswith('read-in'):
            tag = 'read'
        elif tag == 'distopian':
            tag = 'dystopian'

        cleaned_tags.append(tag)

    return ' '.join(set(cleaned_tags))  # remove duplicates
books['tags'] = books['tags'].apply(refine_tags)

In [ ]:
books.head()

,book_id,title,authors,goodreads_book_id,tags
0,2767052,The Hunger Games,Suzanne Collins,2767052,the-hunger-games kindle reviewed survival hung...
1,3,Harry Potter and the Philosopher's Stone,"J.K. Rowling, Mary GrandPré",3,children-s-books kindle owned-books favorite-s...
2,41865,Twilight,Stephenie Meyer,41865,kindle owned-books stephanie-meyer chick-lit f...
3,2657,To Kill a Mockingbird,Harper Lee,2657,kindle owned-books harper-lee race general-fic...
4,4671,The Great Gatsby,F. Scott Fitzgerald,4671,owned-books america romance general-fiction no...

In [ ]:
books['tags'][2]

'kindle owned-books stephanie-meyer chick-lit favorite-series novels all-time-favorites fantasy audiobook vampires ya-romance bookshelf read-more-than-once sries young-adult-fiction completed-series english my-favorites vamps movie my-bookshelf meh re-read books-i-have currently-reading have love-triangle fantasy-paranormal favorite-books to-read reread guilty-pleasures my-library young-adult movies romantic did-not-finish vampire-books never-again twilight-saga high-school audiobooks books library ya-lit books-i-own horror american werewolves love twilight paranormal-romance finished-series stephenie-meyer vampire my-books dnf i-own own-it paranormal abandoned favorite ya-fiction young-adults already-read fiction book-to-movie urban-fantasy scifi shelfari-favorites read supernatural contemporary drama first-in-series book-club pnr stars guilty-pleasure ya-paranormal ebook finished paranormal-fantasy ya-fantasy twilight-series on-my-shelf ya-books teen teen-fiction youngadult'

In [ ]:
books.head()

,book_id,title,authors,goodreads_book_id,tags
0,2767052,The Hunger Games,Suzanne Collins,2767052,the-hunger-games kindle reviewed survival hung...
1,3,Harry Potter and the Philosopher's Stone,"J.K. Rowling, Mary GrandPré",3,children-s-books kindle owned-books favorite-s...
2,41865,Twilight,Stephenie Meyer,41865,kindle owned-books stephanie-meyer chick-lit f...
3,2657,To Kill a Mockingbird,Harper Lee,2657,kindle owned-books harper-lee race general-fic...
4,4671,The Great Gatsby,F. Scott Fitzgerald,4671,owned-books america romance general-fiction no...

In [ ]:
!pip install unidecode
import re
import unidecode

def clean_author(author_str):
    author_str = author_str.lower()                            # lowercase
    author_str = unidecode.unidecode(author_str)               # remove accents
    author_str = re.sub(r'[^\w\s]', '', author_str)            # remove punctuation
    author_str = re.sub(r'\s+', ' ', author_str).strip()       # remove extra spaces
    return author_str

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 7.4 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

In [ ]:
books['authors'] = books['authors'].apply(clean_author)

In [ ]:
books.head(50)

,book_id,title,authors,goodreads_book_id,tags
0,2767052,The Hunger Games,suzanne collins,2767052,the-hunger-games kindle reviewed survival hung...
1,3,Harry Potter and the Philosopher's Stone,jk rowling mary grandpre,3,children-s-books kindle owned-books favorite-s...
2,41865,Twilight,stephenie meyer,41865,kindle owned-books stephanie-meyer chick-lit f...
3,2657,To Kill a Mockingbird,harper lee,2657,kindle owned-books harper-lee race general-fic...
4,4671,The Great Gatsby,f scott fitzgerald,4671,owned-books america romance general-fiction no...
5,11870085,The Fault in Our Stars,john green,11870085,kindle love-story owned-books chick-lit review...
6,5907,The Hobbit or There and Back Again,jrr tolkien,5907,children-s-books on-hold kindle fiction-fantas...
7,5107,The Catcher in the Rye,jd salinger,5107,owned-books america j-d-salinger general-ficti...
8,960,Angels & Demons,dan brown,960,kindle owned-books thrillers crime-thriller cr...
9,1885,Pride and Prejudice,jane austen,1885,on-hold kindle owned-books chick-lit austen br...
10,77203,The Kite Runner,khaled hosseini,77203,kindle owned-books culture general-fiction nov...
11,13335037,Divergent,veronica roth,13335037,series scifi my-bookshelf audiobooks dystopian...
12,5470,Nineteen Eighty-Four,george orwell erich fromm celal uster,5470,satire on-hold kindle owned-books philosophy g...
13,7613,Animal Farm: A Fairy Story,george orwell,7613,satire kindle owned-books philosophy general-f...
14,48855,Het Achterhuis: Dagboekbrieven 14 juni 1942 - ...,anne frank eleanor roosevelt bm mooyaartdoubleday,48855,children-s-books kindle auto-biography bio-mem...
15,2429135,Män som hatar kvinnor,stieg larsson reg keeland,2429135,kindle sweden owned-books thrillers crime-thri...
16,6148028,Catching Fire,suzanne collins,6148028,the-hunger-games kindle survival hunger-games ...
17,5,Harry Potter and the Prisoner of Azkaban,jk rowling mary grandpre rufus beck,5,children-s-books kindle owned-books favorite-s...
18,34,The Fellowship of the Ring,jrr tolkien,34,on-hold kindle fiction-fantasy owned-books tol...
19,7260188,Mockingjay,suzanne collins,7260188,the-hunger-games kindle owned-books survival h...
20,2,Harry Potter and the Order of the Phoenix,jk rowling mary grandpre,2,kindle fiction-fantasy owned-books romance rea...
21,12232938,The Lovely Bones,alice sebold,12232938,ghosts kindle owned-books chick-lit crime-myst...
22,15881,Harry Potter and the Chamber of Secrets,jk rowling mary grandpre,15881,children-s-books kindle owned-books favorite-s...
23,6,Harry Potter and the Goblet of Fire,jk rowling mary grandpre,6,children-s-books kindle owned-books favorite-s...
24,136251,Harry Potter and the Deathly Hallows,jk rowling mary grandpre,136251,children-s-books kindle owned-books romance fa...
25,968,The Da Vinci Code,dan brown,968,kindle owned-books thrillers crime-mystery rom...
26,1,Harry Potter and the Half-Blood Prince,jk rowling mary grandpre,1,children-s-books kindle owned-books romance fa...
27,7624,Lord of the Flies,william golding,7624,kindle owned-books survival philosophy general...
28,18135,An Excellent conceited Tragedie of Romeo and J...,william shakespeare robert jackson,18135,theatre kindle owned-books brit-lit romance ge...
29,8442457,Gone Girl,gillian flynn,8442457,on-hold kindle mystery-thriller-horror owned-b...
30,4667024,The Help,kathryn stockett,4667024,kindle owned-books mississippi chick-lit revie...
31,890,Of Mice and Men,john steinbeck,890,kindle owned-books america general-fiction nov...
32,930,Memoirs of a Geisha,arthur golden,930,kindle owned-books japanese chick-lit wwii cul...
33,10818853,Fifty Shades of Grey,el james,10818853,shades-of-grey owned-books chick-lit virgin-he...
34,865,O Alquimista,paulo coelho alan r clarke,865,kindle owned-books personal-development self-i...
35,3636,The Giver,lois lowry,3636,young-adult-literature y-a owned-books youngad...
36,100915,"The Lion, the Witch and the Wardrobe",cs lewis,100915,children-s-books christian-fiction kindle owne...
37,14050,The Time Traveler's Wife,audrey niffenegger,14050,kindle love-story owned-books chick-lit romanc...
38,13496,A Game of Thrones,george rr martin,13496,on-hold kindle fiction-fantasy owned-books rev...
39,19501,"Eat, pray, love: one woman's search for everyt...",elizabeth gilbert,19501,food kindle bio-memoir owned-books adult-nonfi...
40,28187,The Lightning Thief,rick riordan,28187,children-s-books kindle owned-books favorite-s...
41,1934,Little Women,louisa may alcott,1934,children-s-books kindle owned-books chick-lit ...
42,10210,Jane Eyre,charlotte bronte michael mason,10210,kindle brit-lit romance novels english-literat...
43,15931,The Notebook,nicholas sparks,15931,kindle love-story sparks owned-books chick-lit...
44,4214,Life of Pi,yann martel,4214,kindle owned-books man-booker-prize survival p...
45,43641,Water for Elephants,sara gruen,43641,kindle love-story owned-books kindle-unlimited...
46,19063,The Book Thief,markus zusak,19063,on-hold kindle holocaust owned-books reviewed ...
47,4381,Fahrenheit 451,ray bradbury,4381,kindle owned-books books-about-books philosoph...
48,49041,"New Moon (Twilight, #2)",stephenie meyer,49041,kindle shifters owned-books stephanie-meyer ch...
49,30119,Where the Sidewalk Ends: The Poems and Drawing...,shel silverstein,30119,childhood-memories children-s-books poems book...

In [ ]:
import re

def clean_title(title):
    title = title.lower()
    title = re.sub(r'\([^)]*\)', '', title)  # remove anything in parentheses
    title = re.sub(r'[^a-z0-9\s]', '', title)  # remove special characters
    title = re.sub(r'\s+', ' ', title).strip()  # clean extra spaces
    return title
books['title'] = books['title'].apply(clean_title)

In [ ]:
books.head(50)

,book_id,title,authors,goodreads_book_id,tags
0,2767052,the hunger games,suzanne collins,2767052,the-hunger-games kindle reviewed survival hung...
1,3,harry potter and the philosophers stone,jk rowling mary grandpre,3,children-s-books kindle owned-books favorite-s...
2,41865,twilight,stephenie meyer,41865,kindle owned-books stephanie-meyer chick-lit f...
3,2657,to kill a mockingbird,harper lee,2657,kindle owned-books harper-lee race general-fic...
4,4671,the great gatsby,f scott fitzgerald,4671,owned-books america romance general-fiction no...
5,11870085,the fault in our stars,john green,11870085,kindle love-story owned-books chick-lit review...
6,5907,the hobbit or there and back again,jrr tolkien,5907,children-s-books on-hold kindle fiction-fantas...
7,5107,the catcher in the rye,jd salinger,5107,owned-books america j-d-salinger general-ficti...
8,960,angels demons,dan brown,960,kindle owned-books thrillers crime-thriller cr...
9,1885,pride and prejudice,jane austen,1885,on-hold kindle owned-books chick-lit austen br...
10,77203,the kite runner,khaled hosseini,77203,kindle owned-books culture general-fiction nov...
11,13335037,divergent,veronica roth,13335037,series scifi my-bookshelf audiobooks dystopian...
12,5470,nineteen eightyfour,george orwell erich fromm celal uster,5470,satire on-hold kindle owned-books philosophy g...
13,7613,animal farm a fairy story,george orwell,7613,satire kindle owned-books philosophy general-f...
14,48855,het achterhuis dagboekbrieven 14 juni 1942 1 a...,anne frank eleanor roosevelt bm mooyaartdoubleday,48855,children-s-books kindle auto-biography bio-mem...
15,2429135,mn som hatar kvinnor,stieg larsson reg keeland,2429135,kindle sweden owned-books thrillers crime-thri...
16,6148028,catching fire,suzanne collins,6148028,the-hunger-games kindle survival hunger-games ...
17,5,harry potter and the prisoner of azkaban,jk rowling mary grandpre rufus beck,5,children-s-books kindle owned-books favorite-s...
18,34,the fellowship of the ring,jrr tolkien,34,on-hold kindle fiction-fantasy owned-books tol...
19,7260188,mockingjay,suzanne collins,7260188,the-hunger-games kindle owned-books survival h...
20,2,harry potter and the order of the phoenix,jk rowling mary grandpre,2,kindle fiction-fantasy owned-books romance rea...
21,12232938,the lovely bones,alice sebold,12232938,ghosts kindle owned-books chick-lit crime-myst...
22,15881,harry potter and the chamber of secrets,jk rowling mary grandpre,15881,children-s-books kindle owned-books favorite-s...
23,6,harry potter and the goblet of fire,jk rowling mary grandpre,6,children-s-books kindle owned-books favorite-s...
24,136251,harry potter and the deathly hallows,jk rowling mary grandpre,136251,children-s-books kindle owned-books romance fa...
25,968,the da vinci code,dan brown,968,kindle owned-books thrillers crime-mystery rom...
26,1,harry potter and the halfblood prince,jk rowling mary grandpre,1,children-s-books kindle owned-books romance fa...
27,7624,lord of the flies,william golding,7624,kindle owned-books survival philosophy general...
28,18135,an excellent conceited tragedie of romeo and j...,william shakespeare robert jackson,18135,theatre kindle owned-books brit-lit romance ge...
29,8442457,gone girl,gillian flynn,8442457,on-hold kindle mystery-thriller-horror owned-b...
30,4667024,the help,kathryn stockett,4667024,kindle owned-books mississippi chick-lit revie...
31,890,of mice and men,john steinbeck,890,kindle owned-books america general-fiction nov...
32,930,memoirs of a geisha,arthur golden,930,kindle owned-books japanese chick-lit wwii cul...
33,10818853,fifty shades of grey,el james,10818853,shades-of-grey owned-books chick-lit virgin-he...
34,865,o alquimista,paulo coelho alan r clarke,865,kindle owned-books personal-development self-i...
35,3636,the giver,lois lowry,3636,young-adult-literature y-a owned-books youngad...
36,100915,the lion the witch and the wardrobe,cs lewis,100915,children-s-books christian-fiction kindle owne...
37,14050,the time travelers wife,audrey niffenegger,14050,kindle love-story owned-books chick-lit romanc...
38,13496,a game of thrones,george rr martin,13496,on-hold kindle fiction-fantasy owned-books rev...
39,19501,eat pray love one womans search for everything...,elizabeth gilbert,19501,food kindle bio-memoir owned-books adult-nonfi...
40,28187,the lightning thief,rick riordan,28187,children-s-books kindle owned-books favorite-s...
41,1934,little women,louisa may alcott,1934,children-s-books kindle owned-books chick-lit ...
42,10210,jane eyre,charlotte bronte michael mason,10210,kindle brit-lit romance novels english-literat...
43,15931,the notebook,nicholas sparks,15931,kindle love-story sparks owned-books chick-lit...
44,4214,life of pi,yann martel,4214,kindle owned-books man-booker-prize survival p...
45,43641,water for elephants,sara gruen,43641,kindle love-story owned-books kindle-unlimited...
46,19063,the book thief,markus zusak,19063,on-hold kindle holocaust owned-books reviewed ...
47,4381,fahrenheit 451,ray bradbury,4381,kindle owned-books books-about-books philosoph...
48,49041,new moon,stephenie meyer,49041,kindle shifters owned-books stephanie-meyer ch...
49,30119,where the sidewalk ends the poems and drawings...,shel silverstein,30119,childhood-memories children-s-books poems book...

In [ ]:
books['content'] = books['title'] + ' ' + books['authors'] + ' ' + books['tags']

In [ ]:
books.head()

,book_id,title,authors,goodreads_book_id,tags,content
0,2767052,the hunger games,suzanne collins,2767052,the-hunger-games kindle reviewed survival hung...,the hunger games suzanne collins the-hunger-ga...
1,3,harry potter and the philosophers stone,jk rowling mary grandpre,3,children-s-books kindle owned-books favorite-s...,harry potter and the philosophers stone jk row...
2,41865,twilight,stephenie meyer,41865,kindle owned-books stephanie-meyer chick-lit f...,twilight stephenie meyer kindle owned-books st...
3,2657,to kill a mockingbird,harper lee,2657,kindle owned-books harper-lee race general-fic...,to kill a mockingbird harper lee kindle owned-...
4,4671,the great gatsby,f scott fitzgerald,4671,owned-books america romance general-fiction no...,the great gatsby f scott fitzgerald owned-book...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(books['content'])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [ ]:
indices = pd.Series(books.index, index=books['title']).drop_duplicates()

In [ ]:
indices

title
the hunger games                                                                              0
harry potter and the philosophers stone                                                       1
twilight                                                                                      2
to kill a mockingbird                                                                         3
the great gatsby                                                                              4
                                                                                           ...
bayou moon                                                                                 9995
means of ascent                                                                            9996
the mauritius command                                                                      9997
cinderella ate my daughter dispatches from the frontlines of the new girliegirl culture    9998
the first world war                                                                        9999
Length: 10000, dtype: int64

In [ ]:
import re

def get_recommendations(title, cosine_sim=cosine_sim):
    # Clean input title (remove punctuation and lower it)
    title = title.lower()
    title = re.sub(r'\([^)]*\)', '', title)  # remove series info like (Twilight #2)
    title = re.sub(r'[^a-z0-9\s]', '', title).strip()

    # Find the index of the book in your DataFrame
    idx = indices.get(title)
    if idx is None:
        return "❌ Book not found. Please check the title."

    # Get similarity scores with all other books
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort scores from highest to lowest
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Pick top 10 most similar books (excluding the input book itself)
    sim_scores = sim_scores[1:11]

    # Get book indices
    book_indices = [i[0] for i in sim_scores]

    # Return the recommended book titles
    return books['title'].iloc[book_indices]

In [ ]:
get_recommendations("the first world war")

2833                                   the guns of august
7244                                     a bridge too far
6130                                      the longest day
1419    the rise and fall of the third reich a history...
3630    ghost soldiers the epic account of world war i...
4687                stalingrad the fateful siege 19421943
4748        dday june 6 1944 the climactic battle of wwii
7568           an army at dawn the war in africa 19421943
9720                             berlin the downfall 1945
9520    operation mincemeat the true spy story that ch...
Name: title, dtype: object

In [ ]:
import pickle

# Save the vectorizer
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf, f)

In [ ]:
# Save the TF-IDF matrix
with open('tfidf_matrix.pkl', 'wb') as f:
    pickle.dump(tfidf_matrix, f)

In [ ]:
books.to_csv('books_cleaned.csv', index=False)

In [ ]:
with open("cosine_sim_matrix.pkl", "wb") as f:
    pickle.dump(cosine_sim, f)